
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { String, Int, BigInt, Float, ID, Bytes, Timestamp, Boolean, Int8 } from '@sentio/sdk/store'
import { Entity, Required, One, Many, Column, ListColumn, AbstractEntity, getStore, UpdateValues } from '@sentio/sdk/store'
import { BigDecimal } from '@sentio/bigdecimal'
import { DatabaseSchema } from '@sentio/sdk'







interface VaultSnapshotConstructorInput {
  id: ID;
  deposit_balance: BigInt;
  premium_balance: BigInt;
}
@Entity("VaultSnapshot")
export class VaultSnapshot extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	deposit_balance: BigInt

	@Required
	@Column("BigInt")
	premium_balance: BigInt
  constructor(data: VaultSnapshotConstructorInput) {super()}
  
  
  static update(values: UpdateValues<VaultSnapshotConstructorInput>): Promise<void> {
    return getStore().update(VaultSnapshot, values)
  }
}


interface VaultInfoConstructorInput {
  id: ID;
  d_token: String;
  b_token: String;
  o_token: String;
}
@Entity("VaultInfo")
export class VaultInfo extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	d_token: String

	@Required
	@Column("String")
	b_token: String

	@Required
	@Column("String")
	o_token: String
  constructor(data: VaultInfoConstructorInput) {super()}
  
  
  static update(values: UpdateValues<VaultInfoConstructorInput>): Promise<void> {
    return getStore().update(VaultInfo, values)
  }
}


interface SafuInfoConstructorInput {
  id: ID;
  d_token: String;
  dov_d_token: String;
  dov_b_token: String;
}
@Entity("SafuInfo")
export class SafuInfo extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("String")
	d_token: String

	@Required
	@Column("String")
	dov_d_token: String

	@Required
	@Column("String")
	dov_b_token: String
  constructor(data: SafuInfoConstructorInput) {super()}
  
  
  static update(values: UpdateValues<SafuInfoConstructorInput>): Promise<void> {
    return getStore().update(SafuInfo, values)
  }
}


interface TokenMappingConstructorInput {
  id: ID;
  decimal: BigInt;
  address: String;
}
@Entity("TokenMapping")
export class TokenMapping extends AbstractEntity  {

	@Required
	@Column("ID")
	id: ID

	@Required
	@Column("BigInt")
	decimal: BigInt

	@Required
	@Column("String")
	address: String
  constructor(data: TokenMappingConstructorInput) {super()}
  
  
  static update(values: UpdateValues<TokenMappingConstructorInput>): Promise<void> {
    return getStore().update(TokenMapping, values)
  }
}


const source = `type VaultSnapshot @entity {
  id: ID!
  deposit_balance: BigInt!
  premium_balance: BigInt!
}

type VaultInfo @entity {
  id: ID!
  d_token: String!
  b_token: String!
  o_token: String!
}

type SafuInfo @entity {
  id: ID!
  d_token: String!
  dov_d_token: String!
  dov_b_token: String!
}

type TokenMapping @entity {
  id: ID!
  decimal: BigInt!
  address: String!
}
`
DatabaseSchema.register({
  source,
  entities: {
    "VaultSnapshot": VaultSnapshot,
		"VaultInfo": VaultInfo,
		"SafuInfo": SafuInfo,
		"TokenMapping": TokenMapping
  }
})
